[package]
name = "lambdaworks-stark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
lambdaworks-math = { path = "../../math" }
lambdaworks-crypto = { path = "../../crypto" }
lambdaworks-fft = { path = "../../fft" }
thiserror = "1.0.38"
log = "0.4.17"

[dev-dependencies]
hex = "0.4.3"
criterion = "0.4"
env_logger = "*"
test-log = { version = "0.2.11", features = ["log"] }

[features]
test_fiat_shamir = []

[[bench]]
name = "all_benchmarks"
harness = false

[[bench]]
name = "stark_benchmarks"
harness = false
