[package]
name = "ring-lwe"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lambdaworks-math = { workspace = true, features = ["alloc"] }
rand = "0.8"

[dev-dependencies]
rand_chacha = "0.3"
