[package]
name = "lambdaworks-gpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambdaworks-math = { path = "../math" }
thiserror = "1.0.38"
rand = "0.8.5"
metal = "0.24.0"

[dev-dependencies]
proptest = "1.1.0"
criterion = "0.4.0"
objc = "0.2.7"

[[bench]]
name = "metal_benchmarks"
harness = false
