[package]
name = "lambdaworks-plonk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
lambdaworks-math.workspace = true
lambdaworks-crypto.workspace = true
rayon = { version = "1.8.0", optional = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = { version = "0.10.8", default-features = false }
sha2 = { version = "0.10", default-features = false }
rand = "0.8"
hex = "0.4"

[dev-dependencies]
criterion = "0.5"
rand_chacha = "0.3.1"

[features]
parallel = ["dep:rayon", "lambdaworks-math/parallel", "lambdaworks-crypto/parallel"]

[[bench]]
name = "criterion_prover"

[[bench]]
name = "plonk_prover"
harness = false
