[package]
name = "lambdaworks-gkr-prover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambdaworks-math = { workspace = true }
lambdaworks-crypto = { workspace = true }
lambdaworks-sumcheck = { workspace = true }
thiserror = "1.0"
blake2 = "0.10"
sha3 = "0.10.8"
digest = "0.10"


[lib]
name = "lambdaworks_gkr_prover"
path = "src/lib.rs"
