[package]
name = "lambdaworks-circom-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambdaworks-math = { path = "../../../math" }
lambdaworks-groth16 = { path = "../" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
