[book]
title = "lambdaworks Documentation"
authors = ["Javier Chatruc", "Estefano Bargas", "Mauro Toscano", "Diego Kingston", "Sergio Chouhy", "Agustin Garassino", "Mariano Nicolini"]
language = "en"
src = "src"
description = "A modular cryptographic library focused on zero-knowledge proofs and proving systems"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/lambdaclass/lambdaworks"
edit-url-template = "https://github.com/lambdaclass/lambdaworks/edit/main/docs/{path}"
mathjax-support = true
additional-js = ["mermaid-init.js"]

[output.html.fold]
enable = true
level = 1
