[package]
name = "lambdaworks-sumcheck"
version = "0.1.0"
edition = "2021"


[dependencies]
thiserror = "1.0"
lambdaworks-math = { workspace = true, features = ["std"] }
lambdaworks-crypto.workspace = true
