[package]
name = "lambdaworks-sumcheck"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
lambdaworks-math = { workspace = true, features = ["std"] }
lambdaworks-crypto.workspace = true
lambdaworks-gpu = { workspace = true, optional = true }
metal = { version = "0.31", optional = true }
objc = { version = "0.2", optional = true }
block = { version = "0.1", optional = true }
rayon = { version = "1.7", optional = true }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.5"
pprof = { version = "0.13.0", features = ["criterion", "flamegraph"] }

[features]
default = ["parallel"]
parallel = ["dep:rayon", "lambdaworks-math/parallel"]
metal = ["dep:metal", "dep:objc", "dep:block", "lambdaworks-gpu/metal"]

[[bench]]
name = "sumcheck_bench"
harness = false

[[bench]]
name = "criterion_sumcheck"
harness = false
